//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maison
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capteur
    {
        public int @ref { get; set; }
        public string type { get; set; }
        public string id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateT { get; set; }
    }
}
